package virtualpet;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/** 
 *
 * @author Tifani
 */
public class GameView extends JPanel implements Observer, Runnable {
    private Player player;
    private AnimalView animalView;
    private boolean action = false;
    
    public GameView() {
        this.player = null;
        this.animalView = null;
    }
    
    public void setAnimalView(AnimalView animalView) {
        this.animalView = animalView;
        tAnimal.setText(this.animalView.getAnimal().getName());
        if (this.animalView.getAnimal().getState()==1) { //sedang tidur
            this.bSleep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bWake.png")));
            this.bFeed.setEnabled(false);
            this.bClean.setEnabled(false);
            this.bPlay.setEnabled(false);
        } else {
            this.bSleep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bSleep.png")));
            this.bFeed.setEnabled(true);
            this.bClean.setEnabled(true);
            this.bPlay.setEnabled(true);
        }
    }
    
    public JButton getMainMenuButton() {
        return this.bMainMenu;
    }
    
    public JButton getInventoryButton() {
        return this.bInventory;
    }
    
    public Player getPlayer() {
        return this.player;
    }
    
    @Override
    public void update(String args) {
        //masih belum yang upgrade2 atau tidur
        tCoins.setText(String.valueOf(this.player.getCoins()));
        this.action = true;
        if (args.equals("Not enough food")) {
            JOptionPane.showMessageDialog(this, "Not enough food", "Cannot feed pet", JOptionPane.WARNING_MESSAGE);
        }
    }

    @Override
    public void setSubject(Subject sub) {
        this.player = (Player) sub;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        bPlay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bFeed = new javax.swing.JButton();
        bClean = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bSleep = new javax.swing.JButton();
        tHelloText = new javax.swing.JLabel();
        tAnimal = new javax.swing.JLabel();
        bMainMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bInventory = new javax.swing.JButton();
        iCoins = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tCoins = new javax.swing.JLabel();
        bPlay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bFeed = new javax.swing.JButton();
        bClean = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bSleep = new javax.swing.JButton();
        tHelloText = new javax.swing.JLabel();
        tAnimal = new javax.swing.JLabel();
        bMainMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bInventory = new javax.swing.JButton();
        iCoins = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tCoins = new javax.swing.JLabel();
        bCamera = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 235));
        bPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bPlay.png"))); // NOI18N
        bPlay.setContentAreaFilled(false);
        bPlay.setFocusPainted(false);
        bPlay.setBorderPainted(false);
        bPlay.setPreferredSize(new java.awt.Dimension(133, 46));
        bPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPlayMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Status/Blank.png"))); // NOI18N

        bFeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bFeed.png"))); // NOI18N
        bFeed.setContentAreaFilled(false);
        bFeed.setFocusPainted(false);
        bFeed.setBorderPainted(false);
        bFeed.setPreferredSize(new java.awt.Dimension(133, 46));
        bFeed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFeedMouseClicked(evt);
            }
        });

        bClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bClean.png"))); // NOI18N
        bClean.setContentAreaFilled(false);
        bClean.setBorderPainted(false);
        bClean.setFocusPainted(false);
        bClean.setPreferredSize(new java.awt.Dimension(133, 46));
        bClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCleanMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Status/Blank.png"))); // NOI18N

        bSleep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bSleep.png"))); // NOI18N
        bSleep.setContentAreaFilled(false);
        bSleep.setFocusPainted(false);
        bSleep.setBorderPainted(false);
        bSleep.setPreferredSize(new java.awt.Dimension(133, 46));
        bSleep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSleepMouseClicked(evt);
            }
        });

        tHelloText.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 36)); // NOI18N
        tHelloText.setForeground(new java.awt.Color(186, 95, 125));
        tHelloText.setText("Hello, " + this.player.getPlayerName());

        tAnimal.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 48)); // NOI18N
        tAnimal.setForeground(new java.awt.Color(58, 65, 141));
        tAnimal.setText("");

        bMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bMainMenu.png"))); // NOI18N
        bMainMenu.setContentAreaFilled(false);
        bMainMenu.setFocusPainted(false);
        bMainMenu.setBorderPainted(false);
        bMainMenu.setPreferredSize(new java.awt.Dimension(159, 65));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Status/Blank.png"))); // NOI18N

        bInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bInventory.png"))); // NOI18N
        bInventory.setBorderPainted(false);
        bInventory.setContentAreaFilled(false);
        bInventory.setFocusPainted(false);
        bInventory.setPreferredSize(new java.awt.Dimension(159, 65));

        iCoins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Coins.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Status/Blank.png"))); // NOI18N

        tCoins.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 36)); // NOI18N
        tCoins.setForeground(new java.awt.Color(233, 181, 70));
        tCoins.setText(String.valueOf(this.player.getCoins()));

        bPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bPlay.png"))); // NOI18N
        bPlay.setContentAreaFilled(false);
        bPlay.setBorderPainted(false);
        bPlay.setFocusPainted(false);
        bPlay.setPreferredSize(new java.awt.Dimension(133, 46));
        bPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPlayMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Status/Blank.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Status/Blank.png"))); // NOI18N

        tAnimal.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 48)); // NOI18N
        tAnimal.setForeground(new java.awt.Color(58, 65, 141));
        tAnimal.setText("Fluffy");
   
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Status/Blank.png"))); // NOI18N

        iCoins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Coins.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/Status/Blank.png"))); // NOI18N

        bCamera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bCamera.png"))); // NOI18N
        bCamera.setToolTipText("");
        bCamera.setBorderPainted(false);
        bCamera.setContentAreaFilled(false);
        bCamera.setFocusPainted(false);
        bCamera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCameraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bFeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                        .addComponent(tAnimal)
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tHelloText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(bInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(iCoins)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tCoins)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 57, Short.MAX_VALUE)
                                .addComponent(tAnimal)
                                .addGap(128, 128, 128))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .addComponent(tHelloText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iCoins)
                                    .addComponent(tCoins))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(bFeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCamera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(bClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
    }// </editor-fold>                                                        

    private void bFeedMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        this.player.feedPet();
    }                                  

    private void bPlayMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        this.player.playPet();
    }                                  

    private void bCleanMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        this.player.cleanPet();
    }                                   

    private void bSleepMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        if (this.animalView.getAnimal().getState()==0) { //sedang bangun
            this.animalView.getAnimal().sleep();
            this.bSleep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bWake.png")));
            this.bFeed.setEnabled(false);
            this.bClean.setEnabled(false);
            this.bPlay.setEnabled(false);
        } else {
            this.animalView.getAnimal().wakeUp();
            this.bSleep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualpet/design/bSleep.png")));
            this.bFeed.setEnabled(true);
            this.bClean.setEnabled(true);
            this.bPlay.setEnabled(true);
        }
    }
    
    private void bCameraMouseClicked(java.awt.event.MouseEvent evt) {                                    
        
    } 
    
    @Override
    public void run() {

    }


    // Variables declaration - do not modify
    private javax.swing.JButton bCamera;
    private javax.swing.JButton bClean;
    private javax.swing.JButton bFeed;
    private javax.swing.JButton bInventory;
    private javax.swing.JButton bMainMenu;
    private javax.swing.JButton bPlay;
    private javax.swing.JButton bSleep;
    private javax.swing.JLabel iCoins;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel tAnimal;
    private javax.swing.JLabel tCoins;
    private javax.swing.JLabel tHelloText;
    // End of variables declaration 
    
}


