
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tifani
 */
public class DummyAnimalView extends JPanel {

    /**
     * Creates new form DummyAnimalView
     */
    public DummyAnimalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPlay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bFeed = new javax.swing.JButton();
        tHealthIndex = new javax.swing.JLabel();
        bClean = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bSleep = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tHelloText = new javax.swing.JLabel();
        tAnimal = new javax.swing.JLabel();
        tHungerIndex = new javax.swing.JLabel();
        bMainMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bInventory = new javax.swing.JButton();
        tHappinessIndex = new javax.swing.JLabel();
        iCoins = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tCoins = new javax.swing.JLabel();
        tHygieneIndex = new javax.swing.JLabel();
        iAnimalFullBody = new javax.swing.JLabel();

        bPlay.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bPlay.png")); // NOI18N
        bPlay.setContentAreaFilled(false);
        bPlay.setPreferredSize(new java.awt.Dimension(133, 46));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\progressBar.png")); // NOI18N

        bFeed.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bFeed.png")); // NOI18N
        bFeed.setContentAreaFilled(false);
        bFeed.setPreferredSize(new java.awt.Dimension(133, 46));

        tHealthIndex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tHealthIndex.setForeground(new java.awt.Color(58, 65, 141));
        tHealthIndex.setText("Health:");

        bClean.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bClean.png")); // NOI18N
        bClean.setContentAreaFilled(false);
        bClean.setPreferredSize(new java.awt.Dimension(133, 46));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\progressBar.png")); // NOI18N

        bSleep.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bSleep.png")); // NOI18N
        bSleep.setContentAreaFilled(false);
        bSleep.setPreferredSize(new java.awt.Dimension(133, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\cat5.png")); // NOI18N

        tHelloText.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 36)); // NOI18N
        tHelloText.setForeground(new java.awt.Color(186, 95, 125));
        tHelloText.setText("Hello,");

        tAnimal.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 48)); // NOI18N
        tAnimal.setForeground(new java.awt.Color(58, 65, 141));
        tAnimal.setText("Fluffy");

        tHungerIndex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tHungerIndex.setForeground(new java.awt.Color(58, 65, 141));
        tHungerIndex.setText("Hunger:");

        bMainMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bMainMenu.png")); // NOI18N
        bMainMenu.setContentAreaFilled(false);
        bMainMenu.setPreferredSize(new java.awt.Dimension(159, 65));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\progressBar.png")); // NOI18N

        bInventory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bInventory.png")); // NOI18N
        bInventory.setBorderPainted(false);
        bInventory.setContentAreaFilled(false);
        bInventory.setPreferredSize(new java.awt.Dimension(159, 65));

        tHappinessIndex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tHappinessIndex.setForeground(new java.awt.Color(58, 65, 141));
        tHappinessIndex.setText("Happiness:");

        iCoins.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\Coins.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\progressBar.png")); // NOI18N

        tCoins.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 36)); // NOI18N
        tCoins.setForeground(new java.awt.Color(233, 181, 70));
        tCoins.setText("125");

        tHygieneIndex.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tHygieneIndex.setForeground(new java.awt.Color(58, 65, 141));
        tHygieneIndex.setText("Hgygiene:");

        setPreferredSize(new java.awt.Dimension(233, 300));

        iAnimalFullBody.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\Animal\\Dog\\Happy.png")); // NOI18N
        iAnimalFullBody.setMaximumSize(new java.awt.Dimension(310, 350));
        iAnimalFullBody.setMinimumSize(new java.awt.Dimension(310, 350));
        iAnimalFullBody.setPreferredSize(new java.awt.Dimension(310, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(iAnimalFullBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(iAnimalFullBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClean;
    private javax.swing.JButton bFeed;
    private javax.swing.JButton bInventory;
    private javax.swing.JButton bMainMenu;
    private javax.swing.JButton bPlay;
    private javax.swing.JButton bSleep;
    private javax.swing.JLabel iAnimalFullBody;
    private javax.swing.JLabel iCoins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel tAnimal;
    private javax.swing.JLabel tCoins;
    private javax.swing.JLabel tHappinessIndex;
    private javax.swing.JLabel tHealthIndex;
    private javax.swing.JLabel tHelloText;
    private javax.swing.JLabel tHungerIndex;
    private javax.swing.JLabel tHygieneIndex;
    // End of variables declaration//GEN-END:variables
}
