/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tifani
 */
public class DummyGameView2 extends javax.swing.JPanel {

    /**
     * Creates new form DummyGameView2
     */
    public DummyGameView2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPlay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bFeed = new javax.swing.JButton();
        bClean = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bSleep = new javax.swing.JButton();
        tHelloText = new javax.swing.JLabel();
        tAnimal = new javax.swing.JLabel();
        bMainMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bInventory = new javax.swing.JButton();
        iCoins = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tCoins = new javax.swing.JLabel();
        bPlay1 = new javax.swing.JButton();
        bFeed1 = new javax.swing.JButton();
        bClean1 = new javax.swing.JButton();
        bSleep1 = new javax.swing.JButton();
        tHelloText1 = new javax.swing.JLabel();
        tAnimal1 = new javax.swing.JLabel();
        bMainMenu1 = new javax.swing.JButton();
        bInventory1 = new javax.swing.JButton();
        iCoins1 = new javax.swing.JLabel();
        tCoins1 = new javax.swing.JLabel();
        bCamera = new javax.swing.JButton();

        bPlay.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bPlay.png")); // NOI18N
        bPlay.setContentAreaFilled(false);
        bPlay.setPreferredSize(new java.awt.Dimension(133, 46));
        bPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPlayMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\progressBar.png")); // NOI18N

        bFeed.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bFeed.png")); // NOI18N
        bFeed.setContentAreaFilled(false);
        bFeed.setPreferredSize(new java.awt.Dimension(133, 46));
        bFeed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFeedMouseClicked(evt);
            }
        });

        bClean.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bClean.png")); // NOI18N
        bClean.setContentAreaFilled(false);
        bClean.setPreferredSize(new java.awt.Dimension(133, 46));
        bClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCleanMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\progressBar.png")); // NOI18N

        bSleep.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bSleep.png")); // NOI18N
        bSleep.setContentAreaFilled(false);
        bSleep.setPreferredSize(new java.awt.Dimension(133, 46));
        bSleep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSleepMouseClicked(evt);
            }
        });

        tHelloText.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 36)); // NOI18N
        tHelloText.setForeground(new java.awt.Color(186, 95, 125));
        tHelloText.setText("Hello,");

        tAnimal.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 48)); // NOI18N
        tAnimal.setForeground(new java.awt.Color(58, 65, 141));
        tAnimal.setText("Fluffy");

        bMainMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bMainMenu.png")); // NOI18N
        bMainMenu.setContentAreaFilled(false);
        bMainMenu.setPreferredSize(new java.awt.Dimension(159, 65));
        bMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMainMenuMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\progressBar.png")); // NOI18N

        bInventory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bInventory.png")); // NOI18N
        bInventory.setBorderPainted(false);
        bInventory.setContentAreaFilled(false);
        bInventory.setPreferredSize(new java.awt.Dimension(159, 65));
        bInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bInventoryMouseClicked(evt);
            }
        });

        iCoins.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\Coins.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\progressBar.png")); // NOI18N

        tCoins.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 36)); // NOI18N
        tCoins.setForeground(new java.awt.Color(233, 181, 70));
        tCoins.setText("125");

        bPlay1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bPlay.png")); // NOI18N
        bPlay1.setBorderPainted(false);
        bPlay1.setContentAreaFilled(false);
        bPlay1.setFocusPainted(false);
        bPlay1.setPreferredSize(new java.awt.Dimension(133, 46));
        bPlay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPlay1MouseClicked(evt);
            }
        });

        bFeed1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bFeed.png")); // NOI18N
        bFeed1.setBorderPainted(false);
        bFeed1.setContentAreaFilled(false);
        bFeed1.setFocusPainted(false);
        bFeed1.setPreferredSize(new java.awt.Dimension(133, 46));
        bFeed1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bFeed1MouseClicked(evt);
            }
        });

        bClean1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bClean.png")); // NOI18N
        bClean1.setBorderPainted(false);
        bClean1.setContentAreaFilled(false);
        bClean1.setFocusPainted(false);
        bClean1.setPreferredSize(new java.awt.Dimension(133, 46));
        bClean1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bClean1MouseClicked(evt);
            }
        });

        bSleep1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bSleep.png")); // NOI18N
        bSleep1.setBorderPainted(false);
        bSleep1.setContentAreaFilled(false);
        bSleep1.setFocusPainted(false);
        bSleep1.setPreferredSize(new java.awt.Dimension(133, 46));
        bSleep1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSleep1MouseClicked(evt);
            }
        });

        tHelloText1.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 36)); // NOI18N
        tHelloText1.setForeground(new java.awt.Color(186, 95, 125));
        tHelloText1.setText("Hello,");

        tAnimal1.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 48)); // NOI18N
        tAnimal1.setForeground(new java.awt.Color(58, 65, 141));
        tAnimal1.setText("Fluffy");

        bMainMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bMainMenu.png")); // NOI18N
        bMainMenu1.setBorderPainted(false);
        bMainMenu1.setContentAreaFilled(false);
        bMainMenu1.setFocusPainted(false);
        bMainMenu1.setPreferredSize(new java.awt.Dimension(159, 65));
        bMainMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMainMenu1MouseClicked(evt);
            }
        });

        bInventory1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bInventory.png")); // NOI18N
        bInventory1.setBorderPainted(false);
        bInventory1.setContentAreaFilled(false);
        bInventory1.setFocusPainted(false);
        bInventory1.setPreferredSize(new java.awt.Dimension(159, 65));
        bInventory1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bInventory1MouseClicked(evt);
            }
        });

        iCoins1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\Coins.png")); // NOI18N

        tCoins1.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 36)); // NOI18N
        tCoins1.setForeground(new java.awt.Color(233, 181, 70));
        tCoins1.setText("125");

        bCamera.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tifani\\Documents\\Tifani Warnita\\Schools - College\\ITB\\HMIF ITB\\Informatics Engineering\\Semester 4\\2014\\OOP - Pemrograman Berorientasi Objek\\J-CAT_VirtualPet\\design\\bCamera.png")); // NOI18N
        bCamera.setToolTipText("");
        bCamera.setBorderPainted(false);
        bCamera.setContentAreaFilled(false);
        bCamera.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bFeed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bClean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSleep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                        .addComponent(tAnimal1)
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tHelloText1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bMainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(bInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(iCoins1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tCoins1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 57, Short.MAX_VALUE)
                                .addComponent(tAnimal1)
                                .addGap(128, 128, 128))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .addComponent(tHelloText1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bMainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iCoins1)
                                    .addComponent(tCoins1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(bFeed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bCamera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(bClean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bSleep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bPlayMouseClicked

    private void bFeedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFeedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bFeedMouseClicked

    private void bCleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCleanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bCleanMouseClicked

    private void bSleepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSleepMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bSleepMouseClicked

    private void bMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMainMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bMainMenuMouseClicked

    private void bInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInventoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bInventoryMouseClicked

    private void bPlay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPlay1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bPlay1MouseClicked

    private void bClean1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bClean1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bClean1MouseClicked

    private void bSleep1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSleep1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bSleep1MouseClicked

    private void bMainMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMainMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bMainMenu1MouseClicked

    private void bInventory1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInventory1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bInventory1MouseClicked

    private void bFeed1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFeed1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bFeed1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCamera;
    private javax.swing.JButton bClean;
    private javax.swing.JButton bClean1;
    private javax.swing.JButton bFeed;
    private javax.swing.JButton bFeed1;
    private javax.swing.JButton bInventory;
    private javax.swing.JButton bInventory1;
    private javax.swing.JButton bMainMenu;
    private javax.swing.JButton bMainMenu1;
    private javax.swing.JButton bPlay;
    private javax.swing.JButton bPlay1;
    private javax.swing.JButton bSleep;
    private javax.swing.JButton bSleep1;
    private javax.swing.JLabel iCoins;
    private javax.swing.JLabel iCoins1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel tAnimal;
    private javax.swing.JLabel tAnimal1;
    private javax.swing.JLabel tCoins;
    private javax.swing.JLabel tCoins1;
    private javax.swing.JLabel tHelloText;
    private javax.swing.JLabel tHelloText1;
    // End of variables declaration//GEN-END:variables
}
