/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS X202E
 */
public class InventoryView extends javax.swing.JFrame implements Observer {
    private Player P;
    /**
     * Creates new form InventoryView
     */
    public InventoryView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        foodImage = new javax.swing.JLabel();
        toyImage = new javax.swing.JLabel();
        soapImage = new javax.swing.JLabel();
        soapName = new javax.swing.JLabel();
        inventoryTitle = new javax.swing.JLabel();
        toyName = new javax.swing.JLabel();
        foodName = new javax.swing.JLabel();
        soapDesc = new javax.swing.JLabel();
        upgradeToyButton = new javax.swing.JButton();
        buyFoodButton = new javax.swing.JButton();
        foodDesc = new javax.swing.JLabel();
        toyDesc = new javax.swing.JLabel();
        upgradeToyPrice = new javax.swing.JLabel();
        currentCoins = new javax.swing.JLabel();
        upgradeSoapButton = new javax.swing.JButton();
        upgradeSoapPrice = new javax.swing.JLabel();
        buyFoodPrice = new javax.swing.JLabel();
        upgradeFoodButton = new javax.swing.JButton();
        upgradeFoodPrice = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        jLabel10.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        jLabel10.setText("Increases happiness by 20 points");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 251, 213));
        setMaximumSize(new java.awt.Dimension(800, 480));
        setMinimumSize(new java.awt.Dimension(800, 480));
        getContentPane().setLayout(null);

        foodImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS X202E\\Documents\\GitHub\\J-CAT_VirtualPet\\design\\dogfoodinv.png")); // NOI18N
        getContentPane().add(foodImage);
        foodImage.setBounds(90, 349, 100, 100);
        foodImage.getAccessibleContext().setAccessibleName("Food");

        toyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dogballinv.png"))); // NOI18N
        getContentPane().add(toyImage);
        toyImage.setBounds(90, 109, 100, 100);

        soapImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS X202E\\Documents\\GitHub\\J-CAT_VirtualPet\\design\\soapinv.png")); // NOI18N
        getContentPane().add(soapImage);
        soapImage.setBounds(90, 229, 100, 100);

        soapName.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        soapName.setForeground(new java.awt.Color(184, 86, 120));
        soapName.setText("Medium Soap");
        getContentPane().add(soapName);
        soapName.setBounds(220, 229, 149, 32);
        soapName.getAccessibleContext().setAccessibleName("Soap Name");

        inventoryTitle.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 48)); // NOI18N
        inventoryTitle.setForeground(new java.awt.Color(215, 198, 181));
        inventoryTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorytitle.png"))); // NOI18N
        getContentPane().add(inventoryTitle);
        inventoryTitle.setBounds(268, 11, 319, 87);

        toyName.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        toyName.setForeground(new java.awt.Color(184, 86, 120));
        toyName.setText("Medium Toy");
        getContentPane().add(toyName);
        toyName.setBounds(220, 109, 134, 32);
        toyName.getAccessibleContext().setAccessibleName("Toy Name");

        foodName.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        foodName.setForeground(new java.awt.Color(184, 86, 120));
        foodName.setText("Medium Food");
        getContentPane().add(foodName);
        foodName.setBounds(220, 349, 146, 27);
        foodName.getAccessibleContext().setAccessibleName("Food Name");

        soapDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        soapDesc.setText("Increases hygiene by 20 points");
        getContentPane().add(soapDesc);
        soapDesc.setBounds(220, 264, 277, 19);

        upgradeToyButton.setBackground(new java.awt.Color(46, 112, 185));
        upgradeToyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upgradebutton.png"))); // NOI18N
        upgradeToyButton.setBorderPainted(false);
        upgradeToyButton.setContentAreaFilled(false);
        upgradeToyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upgradeToyButtonMouseClicked(evt);
            }
        });
        getContentPane().add(upgradeToyButton);
        upgradeToyButton.setBounds(220, 169, 108, 42);
        upgradeToyButton.getAccessibleContext().setAccessibleName("UpgradeToyButton");

        buyFoodButton.setBackground(new java.awt.Color(46, 112, 185));
        buyFoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buybutton.png"))); // NOI18N
        buyFoodButton.setBorderPainted(false);
        buyFoodButton.setContentAreaFilled(false);
        buyFoodButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyFoodButtonMouseClicked(evt);
            }
        });
        getContentPane().add(buyFoodButton);
        buyFoodButton.setBounds(220, 412, 72, 38);

        foodDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        foodDesc.setText("Reduces hunger by 20 points");
        getContentPane().add(foodDesc);
        foodDesc.setBounds(220, 382, 259, 19);

        toyDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        toyDesc.setText("Increases happiness by 20 points");
        getContentPane().add(toyDesc);
        toyDesc.setBounds(220, 144, 294, 19);

        upgradeToyPrice.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 18)); // NOI18N
        upgradeToyPrice.setForeground(new java.awt.Color(233, 181, 70));
        upgradeToyPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinsmall.png"))); // NOI18N
        upgradeToyPrice.setText("200");
        getContentPane().add(upgradeToyPrice);
        upgradeToyPrice.setBounds(332, 169, 66, 42);

        currentCoins.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 32)); // NOI18N
        currentCoins.setForeground(new java.awt.Color(233, 181, 70));
        currentCoins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinbig.png"))); // NOI18N
        currentCoins.setText("125");
        getContentPane().add(currentCoins);
        currentCoins.setBounds(655, 33, 96, 43);

        upgradeSoapButton.setBackground(new java.awt.Color(46, 112, 185));
        upgradeSoapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upgradebutton.png"))); // NOI18N
        upgradeSoapButton.setBorderPainted(false);
        upgradeSoapButton.setContentAreaFilled(false);
        upgradeSoapButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upgradeSoapButtonMouseClicked(evt);
            }
        });
        getContentPane().add(upgradeSoapButton);
        upgradeSoapButton.setBounds(220, 289, 108, 42);

        upgradeSoapPrice.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 18)); // NOI18N
        upgradeSoapPrice.setForeground(new java.awt.Color(233, 181, 70));
        upgradeSoapPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinsmall.png"))); // NOI18N
        upgradeSoapPrice.setText("200");
        getContentPane().add(upgradeSoapPrice);
        upgradeSoapPrice.setBounds(332, 289, 66, 42);

        buyFoodPrice.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 18)); // NOI18N
        buyFoodPrice.setForeground(new java.awt.Color(233, 181, 70));
        buyFoodPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinsmall.png"))); // NOI18N
        buyFoodPrice.setText("8");
        getContentPane().add(buyFoodPrice);
        buyFoodPrice.setBounds(296, 412, 40, 42);

        upgradeFoodButton.setBackground(new java.awt.Color(46, 112, 185));
        upgradeFoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upgradebutton.png"))); // NOI18N
        upgradeFoodButton.setBorderPainted(false);
        upgradeFoodButton.setContentAreaFilled(false);
        upgradeFoodButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upgradeFoodButtonMouseClicked(evt);
            }
        });
        getContentPane().add(upgradeFoodButton);
        upgradeFoodButton.setBounds(354, 412, 108, 42);

        upgradeFoodPrice.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 18)); // NOI18N
        upgradeFoodPrice.setForeground(new java.awt.Color(233, 181, 70));
        upgradeFoodPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinsmall.png"))); // NOI18N
        upgradeFoodPrice.setText("200");
        getContentPane().add(upgradeFoodPrice);
        upgradeFoodPrice.setBounds(466, 412, 66, 42);

        backButton.setBackground(new java.awt.Color(46, 112, 185));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backbutton.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(90, 26, 108, 42);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonMouseClicked

    private void upgradeToyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upgradeToyButtonMouseClicked
        P.upgradeToy();
    }//GEN-LAST:event_upgradeToyButtonMouseClicked

    private void upgradeSoapButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upgradeSoapButtonMouseClicked
        P.upgradeSoap();
    }//GEN-LAST:event_upgradeSoapButtonMouseClicked

    private void buyFoodButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyFoodButtonMouseClicked
        P.buyFood(1);
    }//GEN-LAST:event_buyFoodButtonMouseClicked

    private void upgradeFoodButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upgradeFoodButtonMouseClicked
        P.upgradeFood();
    }//GEN-LAST:event_upgradeFoodButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryView().setVisible(true);
            }
        });
    }
    
    @Override
    public void update(Object o) {
        String message=(String)o;
        switch (message) {
            case "UPGRADETOY":
                currentCoins.setText(""+P.getCoins());
                toyName.setText(P.getToy().getName());
                toyDesc.setText(P.getToy().getDescription());
                if (P.getToy().getLevel()==3) {
                    upgradeToyButton.setVisible(false);
                    upgradeToyPrice.setVisible(false);
                } else {
                    upgradeToyPrice.setText(""+P.getToy().getUpgradePrice());
                }   break;
            case "UPGRADESOAP":
                currentCoins.setText(""+P.getCoins());
                soapName.setText(P.getSoap().getName());
                soapDesc.setText(P.getSoap().getDescription());
                if (P.getSoap().getLevel()==3) {
                    upgradeSoapButton.setVisible(false);
                    upgradeSoapPrice.setVisible(false);
                } else {
                    upgradeSoapPrice.setText(""+P.getSoap().getUpgradePrice());
                }   break;
            case "UPGRADEFOOD":
                currentCoins.setText(""+P.getCoins());
                foodName.setText(P.getFood().getName()+" (Qty: "+P.getFood().getQuantity()+")");
                foodDesc.setText(P.getFood().getDescription());
                if (P.getFood().getLevel()==3) {
                    upgradeFoodButton.setVisible(false);
                    upgradeFoodPrice.setVisible(false);
                } else {
                    upgradeFoodPrice.setText(""+P.getFood().getUpgradePrice());
                }   break;
            case "BUYFOOD":
                currentCoins.setText(""+P.getCoins());
                foodName.setText(P.getFood().getName()+" (Qty: "+P.getFood().getQuantity()+")");
                break;
        }
    }

    @Override
    public void setSubject(Subject s) {
        this.P = (Player)s;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buyFoodButton;
    private javax.swing.JLabel buyFoodPrice;
    private javax.swing.JLabel currentCoins;
    private javax.swing.JLabel foodDesc;
    private javax.swing.JLabel foodImage;
    private javax.swing.JLabel foodName;
    private javax.swing.JLabel inventoryTitle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel soapDesc;
    private javax.swing.JLabel soapImage;
    private javax.swing.JLabel soapName;
    private javax.swing.JLabel toyDesc;
    private javax.swing.JLabel toyImage;
    private javax.swing.JLabel toyName;
    private javax.swing.JButton upgradeFoodButton;
    private javax.swing.JLabel upgradeFoodPrice;
    private javax.swing.JButton upgradeSoapButton;
    private javax.swing.JLabel upgradeSoapPrice;
    private javax.swing.JButton upgradeToyButton;
    private javax.swing.JLabel upgradeToyPrice;
    // End of variables declaration//GEN-END:variables
}
