/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS X202E
 */
public class InventoryView extends javax.swing.JFrame {
    /**
     * Creates new form InventoryView
     */
    public InventoryView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        foodImage = new javax.swing.JLabel();
        toyImage = new javax.swing.JLabel();
        soapImage = new javax.swing.JLabel();
        soapName = new javax.swing.JLabel();
        inventoryTitle = new javax.swing.JLabel();
        toyName = new javax.swing.JLabel();
        foodName = new javax.swing.JLabel();
        soapDesc = new javax.swing.JLabel();
        upgradeToyButton = new javax.swing.JButton();
        buyFoodButton = new javax.swing.JButton();
        foodDesc = new javax.swing.JLabel();
        toyDesc = new javax.swing.JLabel();
        upgradeToyPrice = new javax.swing.JLabel();
        currentCoins = new javax.swing.JLabel();
        upgradeSoapButton = new javax.swing.JButton();
        upgradeSoapPrice = new javax.swing.JLabel();
        buyFoodPrice = new javax.swing.JLabel();
        upgradeFoodButton = new javax.swing.JButton();
        upgradeFoodPrice = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        jLabel10.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        jLabel10.setText("Increases happiness by 20 points");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 251, 213));

        foodImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS X202E\\Documents\\GitHub\\J-CAT_VirtualPet\\design\\dogfoodinv.png")); // NOI18N

        toyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dogballinv.png"))); // NOI18N

        soapImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS X202E\\Documents\\GitHub\\J-CAT_VirtualPet\\design\\soapinv.png")); // NOI18N

        soapName.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        soapName.setForeground(new java.awt.Color(184, 86, 120));
        soapName.setText("Medium Soap");

        inventoryTitle.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 48)); // NOI18N
        inventoryTitle.setForeground(new java.awt.Color(215, 198, 181));
        inventoryTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorytitle.png"))); // NOI18N

        toyName.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        toyName.setForeground(new java.awt.Color(184, 86, 120));
        toyName.setText("Medium Toy");

        foodName.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        foodName.setForeground(new java.awt.Color(184, 86, 120));
        foodName.setText("Medium Food");

        soapDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        soapDesc.setText("Increases hygiene by 20 points");

        upgradeToyButton.setBackground(new java.awt.Color(46, 112, 185));
        upgradeToyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upgradebutton.png"))); // NOI18N
        upgradeToyButton.setBorderPainted(false);
        upgradeToyButton.setContentAreaFilled(false);
        upgradeToyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upgradeToyButtonMouseClicked(evt);
            }
        });

        buyFoodButton.setBackground(new java.awt.Color(46, 112, 185));
        buyFoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buybutton.png"))); // NOI18N
        buyFoodButton.setBorderPainted(false);
        buyFoodButton.setContentAreaFilled(false);

        foodDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        foodDesc.setText("Reduces hunger by 20 points");

        toyDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        toyDesc.setText("Increases happiness by 20 points");

        upgradeToyPrice.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 18)); // NOI18N
        upgradeToyPrice.setForeground(new java.awt.Color(233, 181, 70));
        upgradeToyPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinsmall.png"))); // NOI18N
        upgradeToyPrice.setText("200");

        currentCoins.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 32)); // NOI18N
        currentCoins.setForeground(new java.awt.Color(233, 181, 70));
        currentCoins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinbig.png"))); // NOI18N
        currentCoins.setText("125");

        upgradeSoapButton.setBackground(new java.awt.Color(46, 112, 185));
        upgradeSoapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upgradebutton.png"))); // NOI18N
        upgradeSoapButton.setBorderPainted(false);
        upgradeSoapButton.setContentAreaFilled(false);

        upgradeSoapPrice.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 18)); // NOI18N
        upgradeSoapPrice.setForeground(new java.awt.Color(233, 181, 70));
        upgradeSoapPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinsmall.png"))); // NOI18N
        upgradeSoapPrice.setText("200");

        buyFoodPrice.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 18)); // NOI18N
        buyFoodPrice.setForeground(new java.awt.Color(233, 181, 70));
        buyFoodPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinsmall.png"))); // NOI18N
        buyFoodPrice.setText("8");

        upgradeFoodButton.setBackground(new java.awt.Color(46, 112, 185));
        upgradeFoodButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upgradebutton.png"))); // NOI18N
        upgradeFoodButton.setBorderPainted(false);
        upgradeFoodButton.setContentAreaFilled(false);

        upgradeFoodPrice.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 18)); // NOI18N
        upgradeFoodPrice.setForeground(new java.awt.Color(233, 181, 70));
        upgradeFoodPrice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coinsmall.png"))); // NOI18N
        upgradeFoodPrice.setText("200");

        backButton.setBackground(new java.awt.Color(46, 112, 185));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backbutton.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toyImage)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toyDesc)
                                    .addComponent(toyName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(upgradeToyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(upgradeToyPrice))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(soapImage)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soapDesc)
                                    .addComponent(soapName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(upgradeSoapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(upgradeSoapPrice))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foodImage)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foodName)
                                    .addComponent(foodDesc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buyFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buyFoodPrice)
                                        .addGap(18, 18, 18)
                                        .addComponent(upgradeFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(upgradeFoodPrice)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(inventoryTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(currentCoins)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inventoryTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(currentCoins)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toyImage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toyName)
                        .addGap(3, 3, 3)
                        .addComponent(toyDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upgradeToyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upgradeToyPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soapImage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(soapName)
                        .addGap(3, 3, 3)
                        .addComponent(soapDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upgradeSoapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upgradeSoapPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foodImage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(foodName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foodDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upgradeFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyFoodPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buyFoodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upgradeFoodPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        foodImage.getAccessibleContext().setAccessibleName("Food");
        soapName.getAccessibleContext().setAccessibleName("Soap Name");
        toyName.getAccessibleContext().setAccessibleName("Toy Name");
        foodName.getAccessibleContext().setAccessibleName("Food Name");
        upgradeToyButton.getAccessibleContext().setAccessibleName("UpgradeToyButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonMouseClicked

    private void upgradeToyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upgradeToyButtonMouseClicked
        
    }//GEN-LAST:event_upgradeToyButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buyFoodButton;
    private javax.swing.JLabel buyFoodPrice;
    private javax.swing.JLabel currentCoins;
    private javax.swing.JLabel foodDesc;
    private javax.swing.JLabel foodImage;
    private javax.swing.JLabel foodName;
    private javax.swing.JLabel inventoryTitle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel soapDesc;
    private javax.swing.JLabel soapImage;
    private javax.swing.JLabel soapName;
    private javax.swing.JLabel toyDesc;
    private javax.swing.JLabel toyImage;
    private javax.swing.JLabel toyName;
    private javax.swing.JButton upgradeFoodButton;
    private javax.swing.JLabel upgradeFoodPrice;
    private javax.swing.JButton upgradeSoapButton;
    private javax.swing.JLabel upgradeSoapPrice;
    private javax.swing.JButton upgradeToyButton;
    private javax.swing.JLabel upgradeToyPrice;
    // End of variables declaration//GEN-END:variables
}
