
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.border.Border;
import java.awt.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 
 */
public class NewGameView extends JPanel {
    /**
     * Creates new form InventoryView
     */
	private String playerName;
    private String petName;
    private int petType = 0;
	
    public NewGameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	newGameTitle = new JLabel();
    	enterPlayer = new JLabel();
        choosePet = new JLabel();
        enterPet = new JLabel();
        inPlayerName = new JTextField(20);
        inPetName = new JTextField(20);
        startButton = new JButton();
        chooseCatButton = new JButton();
        chooseDogButton = new JButton();
        GroupLayout layout = new GroupLayout(this);
    	
    	setBackground(new java.awt.Color(255, 251, 213));
        setPreferredSize(new java.awt.Dimension(800, 480));
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        
        

        newGameTitle.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 48)); // NOI18N
        newGameTitle.setForeground(new java.awt.Color(215, 198, 181));
        newGameTitle.setIcon(new javax.swing.ImageIcon("design\\Choose\\NewGametitle.png")); // NOI18N
        
        enterPlayer.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        enterPlayer.setForeground(new java.awt.Color(255, 127, 127));
        enterPlayer.setText("Enter your name : ");
        
        Border border = BorderFactory.createLineBorder(new java.awt.Color(215, 198, 181), 5);
        inPlayerName.setBorder(border);
        inPlayerName.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 20));
        inPlayerName.setForeground(new java.awt.Color(113, 98, 86));
        inPetName.setBorder(border);
        inPetName.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 20));
        inPetName.setForeground(new java.awt.Color(113, 98, 86));

        
        choosePet.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        choosePet.setForeground(new java.awt.Color(255, 127, 127));
        choosePet.setText("Choose your pet : ");
        
        enterPet.setFont(new java.awt.Font("GrilledCheese BTN Toasted", 0, 24)); // NOI18N
        enterPet.setForeground(new java.awt.Color(255, 127, 127));
        enterPet.setText("Give your pet a name : ");
       
        
        
        
        
        chooseCatButton.setIcon(new javax.swing.ImageIcon("design\\Choose\\Cat\\choose.png")); // NOI18N
        chooseCatButton.setBorderPainted(false);
        chooseCatButton.setContentAreaFilled(false);
        chooseCatButton.setFocusPainted(false);
        chooseCatButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	chooseCatButtonMouseClicked(evt);
            }    
        });
        
        chooseDogButton.setIcon(new javax.swing.ImageIcon("design\\Choose\\Dog\\choose.png")); // NOI18N
        chooseDogButton.setBorderPainted(false);
        chooseDogButton.setContentAreaFilled(false);
        chooseDogButton.setFocusPainted(false);
        chooseDogButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	chooseDogButtonMouseClicked(evt);
            }    
        });
        
        startButton.setIcon(new javax.swing.ImageIcon("design\\Choose\\bStart.png")); // NOI18N
        startButton.setBorderPainted(false);
        startButton.setContentAreaFilled(false);
        startButton.setFocusPainted(false);
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }    
        });
    
        /*add(newGameTitle);
    	add(enterPlayer);
    	add(inPlayerName);
    	add(choosePet);
    	//add(chooseCatButton);
    	//add(chooseDogButton);
    	add(enterPet);
    	add(inPetName);
    	add(startButton);
    	*/
    	
        layout.setHorizontalGroup(
        	layout.createParallelGroup(GroupLayout.Alignment.CENTER)
        			.addComponent(newGameTitle)
        			.addGroup(layout.createSequentialGroup()
        					.addGap(130)
        					.addComponent(enterPlayer)
        					.addComponent(inPlayerName)
        					.addGap(130))
        			.addGroup(layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(choosePet)
        					.addComponent(chooseCatButton)
           					.addComponent(chooseDogButton))
        			.addGroup(layout.createSequentialGroup()
        					.addGap(130)
        					.addComponent(enterPet)
        					.addComponent(inPetName)
        					.addGap(130))
                	.addComponent(startButton)
        		
        		
        );
        layout.setVerticalGroup(
        		layout.createSequentialGroup()
        			.addComponent(newGameTitle)
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
        					.addComponent(enterPlayer)
        					.addComponent(inPlayerName))
        			.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
        					.addComponent(choosePet)
        					.addComponent(chooseCatButton)
        					.addComponent(chooseDogButton))
        			.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
        					.addComponent(enterPet)
        					.addComponent(inPetName))
        			.addGap(20)
        			.addComponent(startButton)
        			
        		);
        setLayout(layout);
    }
    
    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	if (inPlayerName.getText().equals("") || inPlayerName.getText().equals("") || petType == 0){
    		 JOptionPane.showMessageDialog(this,
                     "Please complete the form to continue",
                     "Incomplete Form",
                     JOptionPane.WARNING_MESSAGE);
    	}
    	else {
    		playerName = inPlayerName.getText();
    		petName = inPetName.getText();
    		//pindah panel
    	}
    }
    
    private void chooseCatButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	chooseDogButton.setIcon(new javax.swing.ImageIcon("design\\Choose\\Dog\\choose.png"));
    	chooseCatButton.setIcon(new javax.swing.ImageIcon("design\\Choose\\Cat\\chosen.png"));
    	
    	petType = 1;
        
        
    }

    private void chooseDogButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	chooseCatButton.setIcon(new javax.swing.ImageIcon("design\\Choose\\Cat\\choose.png"));
    	chooseDogButton.setIcon(new javax.swing.ImageIcon("design\\Choose\\Dog\\chosen.png"));
    	petType = 2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel newGameTitle;
    private JLabel enterPlayer;
    private JLabel choosePet;
    private JLabel enterPet;
    private JTextField inPlayerName;
    private JTextField inPetName;
    private JButton startButton;
    private JButton chooseCatButton;
    private JButton chooseDogButton;
    
    
    
}

